modLoader="javafml"

loaderVersion="[46,)"

license="MIT"

issueTrackerURL="https://marco/AzureMines/issues"

[[mods]]

modId="azuremines"
version="${version}"
displayName="AzureMines"
displayURL="www.youtube.com/c/restonic4"
logoFile="icon.png"
authors="restonic4"
description='''
A mod inspired by a roblox game called Azure mines
'''

[[dependencies.azuremines]]
   modId="forge"
   mandatory=true
   versionRange="[46,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.azuremines]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.azuremines]]
modId="restapi"
mandatory=true
versionRange="[0.4.1,)"
ordering="NONE"
side="BOTH"
